{
 "title": "Madrid - Zaragoza (PostgreSQL)",
 "description": "Business trip planner",
 "time": { "from": "now", "to": "now+90d" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "before", "label": "From Madrid before", "query": "7" },
   { "name": "after", "label": "From Zaragoza after", "query": "15" },
   { "name": "madprice", "label": "From Madrid max price", "query": "30" },
   { "name": "zaprice", "label": "From Zaragoza max price", "query": "30" },
   { "name": "maxprice", "label": "Round Trip Max Price", "query": "40" }
  ]
 },
 "panels": [
  {
   "title": "Last Update",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>{{table}} updated {{update_date}}</center>"
   },
   "targets": [
    {
     "rawSql": "SELECT metadata.table,\n       to_char(metadata.update_date, 'Day DD Month YYYY HH24:MM:SS') AS update_date\nFROM metadata;"
    }
   ]
  },
  {
   "title": "Round Trip",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT concat(to_char(t1.departure_date, 'Day DD/MM/YYYY'), ' ', t1.departure_station, ' - ', t1.return_station, ' ', to_char(t1.departure_date, 'HH24:MI'), ' - ', to_char(t1.return_date, 'HH24:MI')) AS \"Round Trip\",\n       t1.total_price AS current_price,\n       max(t2.total_price) AS max_price,\n       min(t2.total_price) AS min_price\nFROM roundtrips t1,\n     roundtripsts t2\nWHERE t1.departure_station = t2.departure_station\n  AND t1.departure_date = t2.departure_date\n  AND t1.return_station = t2.return_station\n  AND t1.return_date = t2.return_date\n  AND t1.departure_date >= $__timeFrom()\n  AND t1.departure_date < $__timeTo()\n  AND t1.total_price <= $maxprice\nGROUP BY t1.departure_date,\n         t1.departure_station,\n         t1.return_date,\n         t1.return_station,\n         t1.total_price\nORDER BY t1.departure_date ASC,\n         t1.return_date ASC;"
    }
   ]
  },
  {
   "title": "Travel (Madrid - Zaragoza)",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT departure_timestamp  AS t,\n       departure_date as ini,\n       departure_date as end,\n       CONCAT(\n        to_char(departure_date, 'HH24:MI'), '-', to_char(arrival_date, 'HH24:MI'), '. ', price, '€'\n       ) AS title,\n       kind\nFROM trains\nWHERE departure_date >= $__timeFrom()\n  AND departure_date < $__timeTo()\n  AND origin_station = 'Madrid'\n  AND destination_station = 'Zaragoza'\n  AND price IS NOT NULL\n  AND price < $madprice\n  AND CAST(to_char(departure_date, 'HH24') AS DECIMAL)<$before;"
    },
    {
     "rawSql": "SELECT departure_timestamp AS t,\n       departure_date as ini,\n       departure_date as end,\n       CONCAT(\n        to_char(departure_date, 'HH24:MI'), '-', to_char(arrival_date, 'HH24:MI'), '. ', price, '€'\n       ) AS title,\n       kind\nFROM trains\nWHERE departure_date >= $__timeFrom()\n  AND departure_date < $__timeTo()\n  AND origin_station = 'Zaragoza'\n  AND destination_station = 'Madrid'\n  AND price IS NOT NULL\n  AND price < $zaprice\n  AND CAST(to_char(departure_date, 'HH24') AS DECIMAL)>=$after;\n"
    }
   ]
  }
 ]
}